version: '2'
services:
    reda-app:
        image: reda
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://reda-postgresql:5432/REDA
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reda-postgresql:
        extends:
            file: postgresql.yml
            service: reda-postgresql
